[package]
name = "channels"
version = "0.1.0"
authors = ["Luke Burns <lukemburns@gmail.com>"]

[dependencies]
curve25519-dalek = "0.19.0"
sha2 = "0.7.1"
rand = "0.5.5"
failure = "0.1.2"
digest = "0.7.5"
generic-array = "0.11.1"

[dependencies.redschnorr]
path = "../redschnorr"
